name: map_example
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.8.0
  flutter_polyline_points: ^2.1.0
  geocoding: ^3.0.0
  google_maps_apis: ^1.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
